// Objective-C API for talking to gomobile-test/mobile_sdk Go package.
//   gobind -lang=objc -prefix="GomobileTest" gomobile-test/mobile_sdk
//
// File is generated by gobind. Do not edit.

#ifndef __GomobileTestGomobile_test_H__
#define __GomobileTestGomobile_test_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL GomobileTestGomobile_testAdd(long a, long b, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

#endif
