
// Objective-C API for talking to the following Go packages
//
//	gomobile-test/mobile_sdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GomobileTest_FRAMEWORK_H__
#define __GomobileTest_FRAMEWORK_H__

#include "GomobileTestGomobile_test.objc.h"
#include "Universe.objc.h"

#endif
